### ISSUE TITLE
HelloWorld

### ISSUE THREAD

**Issue by NetBUG** [flipperdevices/flipper-hackathon-moscow#1]
### Вы капитан команды?

- [X] Yes, I am a leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

### Подробно опишите идею вашего проекта

Каждая платформа должна иметь хорошо оформленный, красивый HelloWorld.
На правах первонаха предлагаю сабж.

### Готовый проект будет уметь...

Готовый проект будет отображаться в меню, показывать изображение, встроенное при сборке, иметь оформленный репозиторий с документацией.

### GitHub второго участника

@lexfrei

**Comment by zhovner** [comment]
Hellow World уже есть https://github.com/flipperdevices/flipperzero-firmware/blob/dev/lib/app-template/app-template.cpp
