### ISSUE TITLE
Фаззинг управляющего ПО 

### ISSUE THREAD

**Issue by LuciyVI** [flipperdevices/flipper-hackathon-moscow#11]
### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

### Подробно опишите идею вашего проекта

Фаззинг сможет выявлять баги и потенциальные уязвимости управляющего ПО.

### Готовый проект будет уметь...

При сборке прошивки будет будет добавляться инструментация.на ПО будут подоваться случайно сгенерированные данные

**Comment by OlegSchwann** [comment]
> При сборке прошивки
```bash
$ /usr/bin/time --format='%E\n' make all > /dev/null;
1:37
```
При прохождении линтеров, пожалуйста, сборка и так относительно долгая.

**Comment by LuciyVI** [comment]
Сборка для фаззинга не являтся продуктовой версией

**Comment by anna-oake** [comment]
Не можем понять, о чем проект, и какова его цель.
