### ISSUE TITLE
Глушилка радио пультов 315/433/868

### ISSUE THREAD

**Issue by Skorpionm** [flipperdevices/flipper-hackathon-moscow#12]
### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

### Подробно опишите идею вашего проекта

Включил на стоянке, люди нервничают

### Готовый проект будет уметь...

Запуск приложения,
GUI интерфейс
Настройка рабочей частоты

**Comment by zhovner** [comment]
Вредоносный функционал, такое не будем поощрять.
