### ISSUE TITLE
Таймер для Флиппера

### ISSUE THREAD

**Issue by Astrrra** [flipperdevices/flipper-hackathon-moscow#15]
### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

### Подробно опишите идею вашего проекта

Буквально таймер, как на телефоне. Полезен в ситуациях когда телефон не под рукой или занят (как раз часто бывает что на телефоне нельзя поставить таймер потому что на нем будет происходить что-то для чего таймер и нужен, а в фоне его поставить не вариант)

### Готовый проект будет уметь...

Выбор времени от 1с до 23:59:59
Выбор видов сигнала (звук и/или вибрация)
Обратный отсчёт
Сигнал при истечении времени
Отключение сигнала

### GitHub второго участника

@Vital7

### GitHub третьего участника

@SunnyCapt

**Comment by Astrrra** [comment]
Если хватит времени то еще должно быть довольно просто добавить секундомер, но это уже немного не уверена успеем ли за 3 дня с новым железом

**Comment by anna-oake** [comment]
Решили, что слабовато для троих(
Придумайте что-нибудь посмелее!

**Comment by Astrrra** [comment]
Ну раз посмелее...

**Comment by LionZXY** [comment]
Можете присоединиться к идеи сделать часы на флиппере
