### ISSUE TITLE
Морской бой

### ISSUE THREAD

**Issue by alexgr13** [flipperdevices/flipper-hackathon-moscow#18]
### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

### Подробно опишите идею вашего проекта

Классический [морской бой](https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D1%80%D1%81%D0%BA%D0%BE%D0%B9_%D0%B1%D0%BE%D0%B9_(%D0%B8%D0%B3%D1%80%D0%B0))

Расстановка кораблей стрелками + нажатием, длинное нажатие - разворот.
Экран поделён на две половины, слева "своё" поле, справа - поле противника. На своём поле отображаются свои корабли + прострелянные ячейки, на поле противника - прострелянные ячейки + попадания по кораблям + клетки вокруг затопленных кораблей.

Размеры полей - 10 * 10 ячеек, одна ячейка - 6 * 6 пикселей

### Готовый проект будет уметь...

- Одиночная игра против компьютера
- Игра друг против друга по Bluetooth

### GitHub второго участника

@b1rd

**Comment by anna-oake** [comment]
Закрыто в пользу #17.
