### ISSUE TITLE
Вибромассажер с удаленным управлением по Bluetooth

### ISSUE THREAD

**Issue by zhovner** [flipperdevices/flipper-hackathon-moscow#2]
### Вы капитан команды?

- [X] Yes, I am a leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

### Подробно опишите идею вашего проекта

Так как во Флиппере есть вибромотор, его можно использовать как массажер скрытого ношения для интимных мест. Я хочу сделать приложение для мобилы, в котором можно будет удаленно управлять вибромоторчиком на Флиппере. То есть двигать ползунок на телефоне и менять силу вибрации.

### Готовый проект будет уметь...

Приложение на мобильном телефоне, которое подключается к флипперу и включает вибромотор. Сила вибрации регулируется на телефоне ползунком от нуля до максимума.

**Comment by anna-oake** [comment]
Павел, спасибо за вашу идею. К сожалению, эмпирическим тестированием установлено, что вибромотор во Флиппере недостаточно мощный для качественной стимуляции интимных зон. Вынуждены отклонить вашу идею.

**Comment by Astrrra** [comment]
Эх, а идея-то с потенциалом изменить мир была...

**Comment by LionZXY** [comment]
Кажется, мощность BLE сигнала будет низкая при ношении. Вам потребуется в команду hardware разработчик для дополнительной платы, которая будет усиливать сигнал

Я проверю сегодня вечером силу сигнала при ношении внутри и отпишусь в тред

**Comment by NetBUG** [comment]
@aprosvetova можно ли создать issue на доработку hardware в следующей ревизии Флиппера?

**Comment by lomalkin** [comment]
@LionZXY можно проводной сделать и подключать к телефону через OTG / typeC to typeC.

**Comment by Astrrra** [comment]
> @LionZXY можно проводной сделать и подключать к телефону через OTG / typeC to typeC.

Есть оч частый юзкейс когда контроль у партнёра, там провод далеко не всегда подходит

**Comment by LionZXY** [comment]
@lomalkin я уже решил проблему, засунув в себя телефон. Теперь ищу способ управлять удаленно телефоном

**Comment by NetBUG** [comment]
Говори номер

**Comment by bytesex** [comment]
Помогу решить проблему стимуляции интимных зон без этих ваших Флипперов.
Засунувшим в себя телефон респект за тренированность слотов

**Comment by NetBUG** [comment]
Жаль, жаль :(

**Comment by NetBUG** [comment]
![telegram-cloud-photo-size-2-5255828240226957171-y](https://user-images.githubusercontent.com/1539823/143233496-3e368d57-f183-41b3-a37e-050b0aa0cfd0.jpg)
