### ISSUE TITLE
Шагающий шпион FlipWalker

### ISSUE THREAD

**Issue by AlexYurichRobo** [flipperdevices/flipper-hackathon-moscow#21]
### Подробно опишите идею вашего проекта

На базе своего двуногого шагохода - приделать флипперу ноги и возможность перемещаться.
Если хорошо пойдёт, то можно сделать более практичное устройство о 4х ногах.
Робот сможет заходить в кусты и слушать эфир, для обеспечения возможности встать возле дома на закрытую парковку.
Удаленное управление позволит притворяться черепахой и уползать, когда задание будет выполнено

### Готовый проект будет уметь...

Ходить, слушать, анализировать и писать на флешку данные
Маскироваться и уползать в случае опасности

### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

### GitHub второго участника

@KokovkinNR

**Comment by anna-oake** [comment]
Звучит как что-то, что не очень относится к самому Флипперу.
Также приложения Флиппера не могут работать параллельно и собирать информацию в фоне.
