### ISSUE TITLE
Игра по типа электроники/нинтендо: дельфин собирающий ништяки

### ISSUE THREAD

**Issue by skotopes** [flipperdevices/flipper-hackathon-moscow#24]
### Подробно опишите идею вашего проекта

Все знакомы с Электроникой ИМ-02, играли в волка который собирал яйца. Хочу сделать подобное с дельфином.
Сценарий в данном случае не требуется, просто выбрать интересный сеттинг и нарисовать немного ассетов. Игровой движок достаточно простой как раз на день два имплементации и отладки

### Готовый проект будет уметь...

Игру про дельфина аля электроника

### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

**Comment by Skorpionm** [comment]
Если на подобии "Волка и яйца" , неудобно джойстиком будет, а вот "Автослалум" самое то
