### ISSUE TITLE
RF-чат

### ISSUE THREAD

**Issue by forthe94** [flipperdevices/flipper-hackathon-moscow#31]
### Подробно опишите идею вашего проекта

Чат на RF-передатчике.

### Готовый проект будет уметь...

Можно будет обмениваться сообщениями. Связь будет работать между модулями настроенными на одной частоте. Будет возможность включить режим шифрования, чтобы разобрать сообщение можно было только имея ключ.

### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

**Comment by anna-oake** [comment]
Кажется, идея дублирует #13?

**Comment by forthe94** [comment]
Да точно

**Comment by lomalkin** [comment]
Реализация: https://github.com/flipperdevices/flipperzero-firmware/pull/851
