### ISSUE TITLE
"Змейка"

### ISSUE THREAD

**Issue by lacca0** [flipperdevices/flipper-hackathon-moscow#4]
### Вы капитан команды?

- [X] Yes, I am a leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

### Подробно опишите идею вашего проекта

Классическая "Змейка"
https://en.wikipedia.org/wiki/Snake_(video_game_genre)
Используются только кнопки и дисплей

### Готовый проект будет уметь...

 В игре будет 10 уровней, аналогичных классической версии для Nokia 3310 + генератор уровней.

**Comment by LionZXY** [comment]
https://github.com/flipperdevices/flipperzero-firmware/pull/829

**Comment by zhovner** [comment]
Змейка уже есть https://github.com/flipperdevices/flipperzero-firmware/pull/829
