### ISSUE TITLE
Flipper-EUC-Dashboard

### ISSUE THREAD

**Issue by schtangel** [flipperdevices/flipper-hackathon-moscow#41]
### Подробно опишите идею вашего проекта

Использование флиппера в качестве приборной панели для моноколеса.

Девайс должен быть закреплён на перчатке, показывать скорость, процент батареи и ток, а также пищать и трясти райдера за руку при достижении его (колеса) параметрами опасных величин.

Смысл в том, что при достижении максимальной скорости моноколеса, соответствующей стопроцентному заполнению ШИМа его регулятора, колесо перестаёт держать горизонт, а пилот разбивает нос (и не только) об асфальт, что весьма нежелательно.

### Готовый проект будет уметь...

- Подключаться к моноколесу через BLE
- Получать из GATT пакеты со значениями скорости, силы тока, остаточной емкости батареи
- Выводить значения на экран
- Считать скважность ШИМа регулятора из напряжения и скорости
- Пищать и жужжать вибромотором по достижении пороговых значений ШИМ

### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

**Comment by lomalkin** [comment]
Как моноколесник скажу, что это очень полезная штука. Разбор самих протоколов можно позаимствовать из проекта [WheelLog](https://github.com/Wheellog/Wheellog.Android). Голосую за!

**Comment by skotopes** [comment]
У нас BLE, не Bluetooth classic.

**Comment by schtangel** [comment]
Неверно выразился - колесо тоже BLEшное, текущие значения читаются из GATT, в который BT-модуль кладёт то, что контроллер колеса периодически шлёт ему по UART. Заявку поправил.

Судя по заявке про другие жужжалки, высокоуровнего API для этого сейчас нет?

**Comment by anna-oake** [comment]
Автор сдался 🏳
