### ISSUE TITLE
Флиппер-Бипер

### ISSUE THREAD

**Issue by BeanSecurity** [flipperdevices/flipper-hackathon-moscow#43]
### Подробно опишите идею вашего проекта

Плеер DTMF мелодий. Приложение которое будет воспроизводить с динамика флипера DTMF мелодии, набранные с кнопок на экранчике (1234567890*#ABCD) либо из файлов (с форматом файла разберусь позже, наверное будет просто txt с символами 1234567890*#ABCD).

### Готовый проект будет уметь...

- Воспроизводить DTMF мелодии через встроенный динамик
- Загружать мелодии из файлов на флешке и воспроизведить при нажатии на мелодию в списке
- Воспроизводить DTMF звуки в реальном времени с клавиатуры на экране (раскладка как на картинке)
![142858307-f05ec10c-5290-4eec-9043-76f721987abf](https://user-images.githubusercontent.com/17428993/142858580-109e4b94-d9f9-441b-884e-2888e33b2afd.png)

### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

**Comment by okalachev** [comment]
А там есть встроенный динамик?

**Comment by BeanSecurity** [comment]
> А там есть встроенный динамик?

да, пьезо-пипка которая, для такой задачи она словно та самая шляпа (как раз)

**Comment by Skorpionm** [comment]
Есть готовая функция notification способная воспроизводить ноты 
https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/notification/notification-messages-notes.c

**Comment by BeanSecurity** [comment]
> Есть готовая функция notification способная воспроизводить ноты https://github.com/flipperdevices/flipperzero-firmware/blob/dev/applications/notification/notification-messages-notes.c

спасибо, DTMF это двухтоновый сигнал, ноты там насколько я понял это один тон (буквально одна синусоида).
Насколько я себе представляю сейчас с берега, чтобы получить два тона одновременно мне нужно будет как то сформировать особый ШИМ сигнал (никогда не работал с микроконтроллерами и вот етим всем), так что пока это выглядит чуть посложнее чем просто переиспользовать готовый функционал с нотами, но все равно спасибо

**Comment by anna-oake** [comment]
Рекомендую рассмотреть вариант доработки музыкального плеера, который сейчас есть в plugins. Он сейчас только одну мелодию играет.

Заявку пока отправляю в резерв, у нас кончился лимит. Если кто-то сольётся и будут свободные места, пригласим.

**Comment by anna-oake** [comment]
40 из 41 участников одобренных команд зарегистрировались на мероприятие и получили билеты.
К сожалению, это даже больше, чем максимальная вместимость помещения, поэтому никого дополнительно взять не можем.

Не расстраивайтесь и не забрасывайте свою идею, пожалуйста. Мы рассчитываем, что Хакатон пройдёт хорошо, и тогда ещё не раз вернёмся к этому формату.
