### ISSUE TITLE
OBEX-клиент для ИК-порта

### ISSUE THREAD

**Issue by lacca0** [flipperdevices/flipper-hackathon-moscow#44]
### Подробно опишите идею вашего проекта

Хочу реализовать передачу чб картинок на флиппер со старых телефонов, например Ericsson R320s на базе протокола OBEX (ссылка на описание протокола ниже). Если получится, сделать и сервер и передавать картинки с флиппера на флиппер.

http://www.farnell.com/datasheets/306539.pdf

### Готовый проект будет уметь...

Принимать чб картинки. Мб ставить их на заставку.

### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

**Comment by anna-oake** [comment]
Какой транспорт предполагается? BLE, IR, UART, USB/другое?

**Comment by terge-eg** [comment]
IR для ламповости

**Comment by lacca0** [comment]
> Какой транспорт предполагается? BLE, IR, UART, USB/другое?

IR для ламповости

**Comment by anna-oake** [comment]
Почему-то в заголовке проглядела, сорри.

У нас TSOP-75538, почитайте [даташит](https://www.vishay.com/docs/82495/tsop753.pdf).
Он работает с несущей 38 kHz, надо убедиться, подойдёт ли это для реализации OBEX.
Ну и другие ТТХ нашего приёмника посмотрите, может там фильтрации какие-то, я не шарю.

**Comment by anna-oake** [comment]
Наш ИК-ресивер не потянет.
