### ISSUE TITLE
Исполнение Bluetooth уязвимости CarWhisper

### ISSUE THREAD

**Issue by Ximerixx** [flipperdevices/flipper-hackathon-moscow#45]
### Подробно опишите идею вашего проекта

Я думаю каждый знаешь школьников с колонкой которые вечно всех достают...

### Готовый проект будет уметь...

- Исполнять BT CarWhisper
-DDoS определённого мак адреса получателя, если уязвимость не удалась

### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

### GitHub второго участника

@RespectHz

**Comment by anna-oake** [comment]
Аудио по блютусу — это Bluetooth Classic.
У нас только BLE (Bluetooth Low Energy).
