### ISSUE TITLE
Мультиплеерные шашки.

### ISSUE THREAD

**Issue by AlexKrudu** [flipperdevices/flipper-hackathon-moscow#46]
### Подробно опишите идею вашего проекта

Цель проекта - реализовать мультиплеерные шашки для двух игроков на внутреннем экране Флиппера с режимом игры "против компьютера".

 Управление будет осуществляться через встроенную крестовину.

### Готовый проект будет уметь...

У игры будет 2 режима:
1) Против компьютера (опционально с несколькими уровнями сложности)
2) Против человека с другим флиппером.

Для связи с другим флиппером будет использоваться либо BLE, либо радио диапазон.

### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

### GitHub второго участника

@yank0vy3rdna

**Comment by anna-oake** [comment]
Идея хорошая, но у нас пока нет свободных мест :(
Если кто-то откажется от участия, что довольно вероятно, пригласим вас. Пока резерв.

**Comment by AlexKrudu** [comment]
А когда будет ясно, слился кто-то или нет?

**Comment by anna-oake** [comment]
Как только кто-то сольётся :>

После выходных всех попинаем ещё.

**Comment by AlexKrudu** [comment]
Доброго времени суток!Пока никто не слился?

**Comment by anna-oake** [comment]
Нет, даже среди выданных билетов небольшое переполнение. Третьего декабря днем будет точно понятно, но скорее всего все резервные и не рассмотренные заявки будут закрыты, извините :(

Если получится классно, мы обязательно когда-нибудь повторим мероприятие.

**Comment by anna-oake** [comment]
40 из 41 участников одобренных команд зарегистрировались на мероприятие и получили билеты.
К сожалению, это даже больше, чем максимальная вместимость помещения, поэтому никого дополнительно взять не можем.

Не расстраивайтесь и не забрасывайте свою идею, пожалуйста. Мы рассчитываем, что Хакатон пройдёт хорошо, и тогда ещё не раз вернёмся к этому формату.
