### ISSUE TITLE
Приложение-тамогочи

### ISSUE THREAD

**Issue by N0rd1n** [flipperdevices/flipper-hackathon-moscow#48]
### Подробно опишите идею вашего проекта

Приложение чисто для развлечения: ухаживать за кибердельфином.
Предполагается, что приложение повысит интерес к устройству, потому что всегда будет что запустить и во что залипнуть на нем.

### Готовый проект будет уметь...

Стандартные функции тамогочи: дельфина нужно кормить, проявлять внимание. Предполагается небольшая диалоговая схема.

### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

**Comment by anna-oake** [comment]
Это одна из основных функций Флиппера, которая заявлена изначально. Пока не готова полностью, но работа над ней ведется активно.
