### ISSUE TITLE
DOOM

### ISSUE THREAD

**Issue by n30f0x** [flipperdevices/flipper-hackathon-moscow#50]
### Подробно опишите идею вашего проекта

Проект будет реализовывать DOOM-like шутер по технологии RAY-cast.

### Готовый проект будет уметь...

Будет один уровень с врагами, с возможностью ходить и стрелять, с отрисовкой на родном дисплее флиппера и управлением через родные кнопки.

### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

### GitHub второго участника

@lavaFrai

**Comment by M010** [comment]
Если не получится доделать на хакатоне -- готов помочь) Сейчас уже есть команда)

**Comment by anna-oake** [comment]
40 из 41 участников одобренных команд зарегистрировались на мероприятие и получили билеты.
К сожалению, это даже больше, чем максимальная вместимость помещения, поэтому никого дополнительно взять не можем.

Не расстраивайтесь и не забрасывайте свою идею, пожалуйста. Мы рассчитываем, что Хакатон пройдёт хорошо, и тогда ещё не раз вернёмся к этому формату.
