### ISSUE TITLE
Использовать Флиппер в качестве тюнера для (электро-)гитары

### ISSUE THREAD

**Issue by otakubeam** [flipperdevices/flipper-hackathon-moscow#52]
### Подробно опишите идею вашего проекта

В силу своей портативности, Флиппер может стать отличным подспорьем для хакера-музыканта. В рамках проекта предлагается реализовать прошивку, повторяющую функционал хроматического тюнера для электрогитары — например, [такого](https://www.muztorg.ru/produ%D1%81t/A041395). **Микрофон не нужен, неусиленный звуковой сигнал принимается через аналоговый пин прямо со звукоснимателя.** Акустические гитары тоже можно настраивать при наличии пьезоэлектрического звукоснимателя — например, [такого](https://www.muztorg.ru/produ%D1%81t/A131306).

При подключении гитары к GPIO и извлечении звука Флиппер будет показывать ближайшую к полученной частоте ноту, а также знак отклонения — выше или ниже — чтобы понимать, куда крутить. Поэтому **использумые технологии** ограничиваются GUI и интерфейсом GPIO, а также встроенным в микроконтролер АЦП.

В рамках хакатона планируется осуществлять подключение к джек-разъему электрогитары с помощью щупов-крокодилов. Позже можно сделать нормальную гребёнку с 6.35mm разъёмом и напечатать удобный корпус для модуля.

**Претендуем на включение в официальную прошивку.** Почему бы и нет, если команда Флиппера сочтёт это достотчно востребованным кейсом.

В качестве бонусных целей можно:

- показывать, на сколько именно долей тона частота отличается от идеальной,
- настраивать инструмент автоматически по фиксированному "тюнингу", то есть варианту настройки гитары, загружаемому с карты памяти,
- воспроизводить желаемую ноту с помощью динамика,
- светодиодом показывать попадание в ноту, зажигая красный или зелёный сигнал.

### Готовый проект будет уметь...

- принять и обработать неусиленный звуковой сигнал с электрогитары,
- определить частоту основной гармоники,
- отобразить на дисплее обозначение ближайшей к этой частоте музыкальной ноты (буквы A-G, символы # и b, целочисленный номер октавы),
- отобразить на дисплее знак отклонения от ближайшей ноты (символы +/-).

### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

**Comment by anna-oake** [comment]
40 из 41 участников одобренных команд зарегистрировались на мероприятие и получили билеты.
К сожалению, это даже больше, чем максимальная вместимость помещения, поэтому никого дополнительно взять не можем.

Не расстраивайтесь и не забрасывайте свою идею, пожалуйста. Мы рассчитываем, что Хакатон пройдёт хорошо, и тогда ещё не раз вернёмся к этому формату.
