### ISSUE TITLE
Менеджер паролей

### ISSUE THREAD

**Issue by apatrushev** [flipperdevices/flipper-hackathon-moscow#53]
### Подробно опишите идею вашего проекта

* Флиппер представляется по USB как композитное устройство HID клавиатура + Serial
* Через Serial есть возможность сохранить пароль в Флиппер
* При нажатии кнопки на Флиппере происходит посимвольный набор сохранённого в нём пароля

Теоретическое развитие:
* Управление множеством паролей через Serial интерфейс
* Запрос конкретного пароля через Serial интерфейс, подтверждение с помощью кнопок Флиппера
* Генерация паролей на стороне Флиппера
* Плагин для браузера для ввода пароля по запросу

### Готовый проект будет уметь...

* приложение python cli (пакет, устанавливающийся через pip) для задания пароля через serial
* при подключении Флиппера к компьютеру будет возможность передать с него пароль как будто он был введён с клавиатуры

### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

**Comment by anna-oake** [comment]
40 из 41 участников одобренных команд зарегистрировались на мероприятие и получили билеты.
К сожалению, это даже больше, чем максимальная вместимость помещения, поэтому никого дополнительно взять не можем.

Не расстраивайтесь и не забрасывайте свою идею, пожалуйста. Мы рассчитываем, что Хакатон пройдёт хорошо, и тогда ещё не раз вернёмся к этому формату.
