### ISSUE TITLE
Эмуляция Mifare Zero 1k 2k 4k с перезаписываемым 0 сектором.

### ISSUE THREAD

**Issue by MisteRun** [flipperdevices/flipper-hackathon-moscow#56]
### Подробно опишите идею вашего проекта

Хочу сделать удобную эмуляцию Mifare Zero 1k 2k и 4к, а так же Untralight для возможности клонирования карт и изменения 0 сектора (хранение зав номера карт). Так же написать удобный менеджер карт на подобии google pay, apple pay. За основу хочу взять MIFARE++ Ultralight и MIFAFE Classic Tool.

### Готовый проект будет уметь...

Хочу сделать удобную эмуляцию Mifare Zero 1k 2k и 4к, а так же Untralight для возможности клонирования карт и изменения 0 сектора (хранение зав номера карт). Так же написать удобный менеджер карт на подобии google pay, apple pay. За основу хочу взять MIFARE++ Ultralight и MIFAFE Classic Tool.

### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

**Comment by anna-oake** [comment]
Это запланированная штатная функция.
