### ISSUE TITLE
Использование Flipper в качестве носителя Рутокен

### ISSUE THREAD

**Issue by MisteRun** [flipperdevices/flipper-hackathon-moscow#57]
### Подробно опишите идею вашего проекта

Хочу сделать возможным, использование Flipper'ом в качестве носителя Рутокен

### Готовый проект будет уметь...

В готовом проекте Flipper должен уметь работать как носитель Рутокен с возможностью выбора типа носителя (2.0, Lite, S и т.д.) В приоритете добиться работы с типом 2.0. Иметь удобный интерфейс менеджера выбора носителя и сертификата пользователя. Так же flipper должен иметь расширенный редактор носителя и сертификата (смена номера носителя + изменение пин-кода сертификата). Возможность создания виртуального носителя под нужными параметрами пользователя.

### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

**Comment by anna-oake** [comment]
К сожалению, лимит на количество одобренных проектов превышен. Резерв тоже переполнен.

**Comment by alexey-gamov** [comment]
Идея классная, надеюсь в будущем идею не забросите и реализуете!

**Comment by Sobieg** [comment]
Классная идея!

**Comment by MisteRun** [comment]
Жалко что не пригласили на хакатрон. Хотел детальнее описать проект и может найти команду для реализации этой идеи.

**Comment by anna-oake** [comment]
Нет мест.

**Comment by Sobieg** [comment]
Я думаю, можно попробовать реализовать после получения устройств.

**Comment by MisteRun** [comment]
Вот именно, приходится ждать. Другие же по блату получают устройства ранее и могут реализовывать свои и чужие ранее других))

**Comment by anna-oake** [comment]
Не по блату, а вовремя подав заявку.

**Comment by Sobieg** [comment]
> Вот именно, приходится ждать. Другие же по блату получают устройства ранее и могут реализовывать свои и чужие ранее других))

Я думаю, идей на всех хватит. Кроме того, кажется, что целиком рутокен за несколько дней не сделать. Такие проекты могут и дождаться.
