### ISSUE TITLE
Использовать flipper в качестве WiFi захватчика и глушителя интернета 

### ISSUE THREAD

**Issue by MisteRun** [flipperdevices/flipper-hackathon-moscow#58]
### Подробно опишите идею вашего проекта

Использовать flipper в качестве WiFi захватчика пакетов и глушителя интернета. Научить flipper выискивать в незашифрованных пакетах логины и пароли и записывать их в отдельный текстовый файл.

### Готовый проект будет уметь...

Победой будет считаться тогда, если flipper сможет работать в качестве WiFi захватчика пакетов и глушителя интернета. Научится выискивать в незашифрованных пакетах логины и пароли и записывать их в отдельный текстовый файл. После победы над проектом, будем добавлять новые фишки к примеру: DNS Spoofing, HSTS Spoofing и SSL Strip.

### Вы капитан команды?

- [X] Yes, I am the leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

**Comment by anna-oake** [comment]
Во Флиппере нет Wi-Fi. Также лимит на количество одобренных проектов превышен. Резерв тоже переполнен.
