### ISSUE TITLE
Щупы для iButton

### ISSUE THREAD

**Issue by OlegSchwann** [flipperdevices/flipper-hackathon-moscow#8]
### Вы капитан команды?

- [X] Yes, I am a leader of my team

### Вы готовы приехать на Хакатон в Москву?

- [X] Yes, my team will attend

### Подробно опишите идею вашего проекта

iButton флиппера создан для идеальных условий. Открыть им грязный и старый домофон моего дома просто мучение. Контакты Флиппера слишком маленькие и короткие.

Хочу, что бы можно было воспользоваться [проводом "папа-папа"](https://aliexpress.ru/item/4000204863216.html), через GPIO.

### Готовый проект будет уметь...

В приложении iButton рядом с пунктом "Emulate" появится пункт меню "Emulate on GPIO(1,2)".
Воткнутая в разъемы 1 и 2 пара проводов открывает домофон, даже если приходится поскрести грязь для получения контакта.

**Comment by anna-oake** [comment]
Это уже работает. Достаточно воткнуть провода в GND и GPIO17, пин подписан шелкографией на задней крышке Флиппера.

**Comment by OlegSchwann** [comment]
Это определенно стоит написать более явно, возможно даже в самом пункте меню.

**Comment by anna-oake** [comment]
Пока указано на [схеме GPIO](https://flipperzero.one/#rec240744058), позже добавим в [документацию](https://docs.flipperzero.one/ru).
